### ISSUE TITLE
You should name this repository something different...

### ISSUE THREAD

**Issue by jaredthecoder** [VolSec/Arepository#1]
what is a repository? @JordanHolland

**Comment by JordanHolland** [comment]
re·pos·i·to·ry
rəˈpäzəˌtôrē/
noun
a place, building, or receptacle where things are or may be stored.
"a deep repository for nuclear waste"
a place in which something, especially a natural resource, has accumulated or where it is found in significant quantities.
"accessible repositories of water"
COMPUTING
a central location in which data is stored and managed.
"the metadata will be aggregated in a repository"
